name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bib
    - name: Run Docker
      run: docker run -v ${PWD}:/data bib
    - name: What OS is running
      run: uname -a
    - name: ls
      run: cd data & ls
    - name: bibetextmake
      run: sh publist.sh
