name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bib
    - name: Run Docker
      uses: ./
      run: docker run -v ${PWD}:/data bib uname -a
    - name: What OS is running
      run: uname -a
    - name: ls
      run:  docker run -v ${PWD}:/data bib cd data & ls
    - name: bibetextmake
      run: docker run -v ${PWD}:/data bib /data/publist.sh
