name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@master
    - name: What OS is running
      run: uname -a
    - name: ls
      run:  ls
    - name: install bibtext
      run: apt install -y bibtex2html
    - name: bibetextmake
      run: sh publist.sh
